services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - PYTHONPATH=/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload